### ISSUE TITLE
`expect` type after solving dynamics

### ISSUE THREAD

**Issue by ytdHuang** [qutip/QuantumToolbox.jl#143]
# `sol.states`
In `qutip`, the results is stored depends on `e_ops`:
- if `e_ops` is specified: don't return states at each time point (even the final state, so `sol.states = []`)
- if `e_ops` is not specified: return states at each time point

I think we should also do the same thing.

However, if the keyword argument `saveat` is given, we can still store the state even `e_ops` is given

**Comment by albertomercurio** [comment]
Personally, I don’t like this QuTiP feature. I should have the ability to independent choose what to save. In QuTiP you have to define an option argument to save also the states when saving also `e_ops`. This is very redundant.

What I think is that, yes, we have to make this package as similar as possible to QuTiP, but we don’t have to decrease performances or programming simplicity. In my opinion, the current implementation seems much simpler than the QuTiP one.
