### ISSUE TITLE
Lazy way to create `QobjEvo`

### ISSUE THREAD

**Issue by ytdHuang** [qutip/QuantumToolbox.jl#281]
### Problem Description

Suppose we have three coefficients and operators:
```julia
coef1(p, t) = sin(t)
coef2(p, t) = cos(t)
coef3(p, t) = exp(-t)

X = sigmax()
Y = sigmay()
Z = sigmaz()
```

This is the current way we will do to create the `QobjEvo`:
```julia
H = QobjEvo((Z, (X, coef1), (Y, coef2), (Z, coef3)))
```

If one has plenty of coefficients and operators, which might need to construct the `Tuple` using for-loop or some iterative methods.

However, there is another intuitive way to do that by using `+` or `+=`, like:

```julia
H = Z
H += QobjEvo(((X, coef1),))
H += QobjEvo(((Y, coef2),))
H += QobjEvo(((Z, coef3),))
```

Although it might be a little bit inefficient compare to the standard method, but this is quite intuitive and convenient.

As you can see, even for single operator with coefficient, we still need to put it inside many tuples.

Therefore, I suggest to make the following code work:

```julia
H = Z + QobjEvo(X, coef1) + QobjEvo(Y, coef2) + QobjEvo(Z, coef3)
```

### Proposed Solution

If user is trying to construct `QobjEvo` with a single time-dependent operator, we can construct the `Tuple` intrinsically for the user:

```julia
QuantumObjectEvolution(
    op::QuantumObject,
    f::Function,
    α::Union{Nothing,Number} = nothing;
    type::Union{Nothing,QuantumObjectType} = nothing
) = QuantumObjectEvolution(((op, f),), α, type = type)

# same thing for synonym QobjEvo
```

**Comment by albertomercurio** [comment]
Yes, it could be an option. The `α` argument is not needed here, since the input is still a `QuantumObject` and we can directly multiply it by the scalar.
