### ISSUE TITLE
num_expect=0 although evolution can run

### ISSUE THREAD

**Issue by ferrispnugraha** [qutip/QuantumToolbox.jl#332]
### Bug Description

Run a simple evolution, not recording the expectation value

### Code to Reproduce the Bug

```julia
using QuantumToolbox

H = 2 * π * 0.1 * sigmax()
ψ0 = basis(2, 0) # spin-up
tlist = LinRange(0.0, 10.0, 20)

prob = sesolveProblem(H, ψ0, tlist, e_ops = [sigmaz()])
sol = sesolve(prob)
```

### Code Output

```shell
Progress: [==============================] 100.0% --- Elapsed Time: 0h 00m 02s (ETA: 0h 00m 00s)

Solution of time evolution
(return code: Success)
--------------------------
num_states = 1
num_expect = 0
ODE alg.: OrdinaryDiffEqTsit5.Tsit5{typeof(OrdinaryDiffEqCore.trivial_limiter!), typeof(OrdinaryDiffEqCore.trivial_limiter!), Static.False}(OrdinaryDiffEqCore.trivial_limiter!, OrdinaryDiffEqCore.trivial_limiter!, static(false))
abstol = 1.0e-8
reltol = 1.0e-6
```

### Expected Behaviour

As in https://qutip.org/QuantumToolbox.jl/stable/users_guide/time_evolution/sesolve

Solution of time evolution
(return code: Success)
--------------------------
num_states = 1
num_expect = 1
ODE alg.: OrdinaryDiffEqTsit5.Tsit5{typeof(OrdinaryDiffEqCore.trivial_limiter!), typeof(OrdinaryDiffEqCore.trivial_limiter!), Static.False}(OrdinaryDiffEqCore.trivial_limiter!, OrdinaryDiffEqCore.trivial_limiter!, static(false))
abstol = 1.0e-8
reltol = 1.0e-6

### Your Environment

```shell
QuantumToolbox.jl: Quantum Toolbox in Julia
≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡
Copyright © QuTiP team 2022 and later.
Current admin team:
    Alberto Mercurio and Yi-Te Huang

Package information:
====================================
Julia              Ver. 1.11.1
QuantumToolbox     Ver. 0.22.0
SciMLOperators     Ver. 0.3.12
LinearSolve        Ver. 2.38.0
OrdinaryDiffEqCore Ver. 1.13.0

System information:
====================================
OS       : Windows (x86_64-w64-mingw32)
CPU      : 20 × 12th Gen Intel(R) Core(TM) i7-12700H
Memory   : 31.679 GB
WORD_SIZE: 64
LIBM     : libopenlibm
LLVM     : libLLVM-16.0.6 (ORCJIT, alderlake)
BLAS     : libopenblas64_.dll (ilp64)
Threads  : 1 (on 20 virtual cores)
```

### Additional Context

```julia
expt_z = real(sol.expect[1,:]) 
expt_y = real(sol.expect[2,:])
```
returns the following error (expect is empty):
```
MethodError: no method matching getindex(::Nothing, ::Int64, ::Colon)
The function `getindex` exists, but no method is defined for this combination of argument types.
```

**Comment by albertomercurio** [comment]
Very strange, the code works for me. 

```julia-REPL
julia> sol = sesolve(prob)
Progress: [==============================] 100.0% --- Elapsed Time: 0h 00m 04s (ETA: 0h 00m 00s)
Solution of time evolution
(return code: Success)
--------------------------
num_states = 1
num_expect = 1
ODE alg.: OrdinaryDiffEqTsit5.Tsit5{typeof(OrdinaryDiffEqCore.trivial_limiter!), typeof(OrdinaryDiffEqCore.trivial_limiter!), Static.False}(OrdinaryDiffEqCore.trivial_limiter!, OrdinaryDiffEqCore.trivial_limiter!, static(false))
abstol = 1.0e-8
reltol = 1.0e-6
```

```julia-REPL
julia> QuantumToolbox.versioninfo()

 QuantumToolbox.jl: Quantum Toolbox in Julia
≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡
Copyright © QuTiP team 2022 and later.
Current admin team:
    Alberto Mercurio and Yi-Te Huang

Package information:
====================================
Julia              Ver. 1.11.2
QuantumToolbox     Ver. 0.23.0
SciMLOperators     Ver. 0.3.11
LinearSolve        Ver. 2.38.0
OrdinaryDiffEqCore Ver. 1.13.0

System information:
====================================
OS       : Linux (x86_64-linux-gnu)
CPU      : 32 × 13th Gen Intel(R) Core(TM) i9-13900KF
Memory   : 62.514 GB
WORD_SIZE: 64
LIBM     : libopenlibm
LLVM     : libLLVM-16.0.6 (ORCJIT, alderlake)
BLAS     : libopenblas64_.so (ilp64)
Threads  : 16 (on 32 virtual cores)
```

I see that you are using Windows. Maybe it's related to that. But I doubt because we should have runtests also for windows machines.

**Comment by ytdHuang** [comment]
> ### Bug Description
> Run a simple evolution, not recording the expectation value
> 
> ### Code to Reproduce the Bug
> ```julia
> using QuantumToolbox
> 
> H = 2 * π * 0.1 * sigmax()
> ψ0 = basis(2, 0) # spin-up
> tlist = LinRange(0.0, 10.0, 20)
> 
> prob = sesolveProblem(H, ψ0, tlist, e_ops = [sigmaz()])
> sol = sesolve(prob)
> ```
> 
> ### Code Output
> ```shell
> Progress: [==============================] 100.0% --- Elapsed Time: 0h 00m 02s (ETA: 0h 00m 00s)
> 
> Solution of time evolution
> (return code: Success)
> --------------------------
> num_states = 1
> num_expect = 0
> ODE alg.: OrdinaryDiffEqTsit5.Tsit5{typeof(OrdinaryDiffEqCore.trivial_limiter!), typeof(OrdinaryDiffEqCore.trivial_limiter!), Static.False}(OrdinaryDiffEqCore.trivial_limiter!, OrdinaryDiffEqCore.trivial_limiter!, static(false))
> abstol = 1.0e-8
> reltol = 1.0e-6
> ```
> 
> ### Expected Behaviour
> As in https://qutip.org/QuantumToolbox.jl/stable/users_guide/time_evolution/sesolve
> 
> ## Solution of time evolution
> (return code: Success)
> num_states = 1 num_expect = 1 ODE alg.: OrdinaryDiffEqTsit5.Tsit5{typeof(OrdinaryDiffEqCore.trivial_limiter!), typeof(OrdinaryDiffEqCore.trivial_limiter!), Static.False}(OrdinaryDiffEqCore.trivial_limiter!, OrdinaryDiffEqCore.trivial_limiter!, static(false)) abstol = 1.0e-8 reltol = 1.0e-6
> 
> ### Your Environment
> ```shell
> QuantumToolbox.jl: Quantum Toolbox in Julia
> ≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡
> Copyright © QuTiP team 2022 and later.
> Current admin team:
>     Alberto Mercurio and Yi-Te Huang
> 
> Package information:
> ====================================
> Julia              Ver. 1.11.1
> QuantumToolbox     Ver. 0.22.0
> SciMLOperators     Ver. 0.3.12
> LinearSolve        Ver. 2.38.0
> OrdinaryDiffEqCore Ver. 1.13.0
> 
> System information:
> ====================================
> OS       : Windows (x86_64-w64-mingw32)
> CPU      : 20 × 12th Gen Intel(R) Core(TM) i7-12700H
> Memory   : 31.679 GB
> WORD_SIZE: 64
> LIBM     : libopenlibm
> LLVM     : libLLVM-16.0.6 (ORCJIT, alderlake)
> BLAS     : libopenblas64_.dll (ilp64)
> Threads  : 1 (on 20 virtual cores)
> ```
> 
> ### Additional Context
> ```julia
> expt_z = real(sol.expect[1,:]) 
> expt_y = real(sol.expect[2,:])
> ```
> 
> returns the following error (expect is empty):
> 
> ```
> MethodError: no method matching getindex(::Nothing, ::Int64, ::Colon)
> The function `getindex` exists, but no method is defined for this combination of argument types.
> ```

There is a bug somewhere in the `SciML` packages, I'm not sure which one.
But I solved this problem by updating every package in my `Julia` environment:

just open `Julia`, and then 

or

```julia
pkg> update
```

```julia
using Pkg; Pkg.update()
```

**Comment by ytdHuang** [comment]
By the way, before you update everything. Would you mind to paste the detailed output of your julia package environment ?

This can be obtained by:

```julia
using Pkg; Pkg.status(; mode = PKGMODE_MANIFEST)
```

I just want to record this.
