### ISSUE TITLE
Add support for ProgressBar for mcsolve

### ISSUE THREAD

**Issue by albertomercurio** [qutip/QuantumToolbox.jl#47]
The `ProgressBar` was just implemented. However, it currently supports only `sesolve` and `mesolve`. The support for mcsolve is not straightforward since it has to support Distributed EnsembleProblem is a type stable way. For the moment, the use of `RemoteChannel` to perform this, seems to make the ODE type unstable.

**Comment by ytdHuang** [comment]
I noticed that (in the runtest) some of the progress bar will add a change line (`\n`) after the process is done, some of them won't.

**Comment by ytdHuang** [comment]
Did we finish this in #212 ?

**Comment by albertomercurio** [comment]
No the problem is to support distributed ensembles, where we should use a RemoteChannel for that. 

We need RemoteChannel because in the distributed ensemble the progress bar variable is not shared, but it is copied among all the workers.

In the past it was giving type instabilities, I don't know if it is solved. We should try again.
