### ISSUE TITLE
Write a detailed `README` file

### ISSUE THREAD

**Issue by albertomercurio** [qutip/QuantumToolbox.jl#79]
I think that a detailed `README` file is needed.

The file should explain the potentialities of this package

- Syntax very close to the QuTiP one
- Very fast simulations thanks to Julia
- Easy to extend
- Support for GPUs
- Support for Distributed computing

And making also some examples such as 

- The master equation in CPU (showing the similarities to QuTiP) and in the GPU (showing how easy is to perform fast simulations)
- The Distributed computing of quantum trajectories

**Comment by ytdHuang** [comment]
Sure, I think we can do this after moving to `QuTiP` org.
Since we also need to change the links of the runtests, codecov, and documentation badges after that.

**Comment by ytdHuang** [comment]
Maybe we can follow the similar structure of [`README.md`](https://github.com/qutip/qutip/blob/master/README.md) in `QuTiP`

**Comment by ytdHuang** [comment]
@albertomercurio 
Should we close this one ?

**Comment by albertomercurio** [comment]
Yes
