### ISSUE TITLE
Add a the iterative solvers and eigensolver for `steadystate`

### ISSUE THREAD

**Issue by albertomercurio** [qutip/QuantumToolbox.jl#81]
There is only one [`steadystate`](https://github.com/qutip/QuantumToolbox.jl/blob/a227f5f088e555d25810f7ab519d2b860d5f8735/src/steadystate.jl#L15) solver: the direct solver.

It could be very useful to add other solvers, such as all the iterative solvers that are available through the [**LinearSolve.jl**](https://github.com/SciML/LinearSolve.jl) package and the internal [*eigensolver*](https://github.com/qutip/QuantumToolbox.jl/blob/a227f5f088e555d25810f7ab519d2b860d5f8735/src/eigsolve.jl#L367).

The eigensolver uses the internal sparse solver, that uses the Krylov subspace, taking only the eigenstate with zero eigenvalue.

Perhaps, one can also add the support for a cache (it could be very easy using the **LinearSolve.jl** package).

**Comment by golanor** [comment]
Hi,

I'm trying to understand how to approach this. Is the idea to perform different types of eigendecompositions of the Lindblandian, and then return the eigenstate with zero eigenvalue?

**Comment by albertomercurio** [comment]
Hi,

the idea is to add other solvers to the `steadystate` function. We might have two different main methods:
- A linear solver method (using **LinearSolve.jl** perhaps)
- An eigensolver method

The **LinearSolve.jl** has different methods inside, and so we can choose several sub methods from it. For example, this package is able to solve a linear system using both the direct solver or the iterative solvers.

Regarding the eigensolver, yes, you can solve the Liouvillian eigenvalues and then take the eigenstate with zero eigenvalue. You can use the internal `eigsolve` function, that is very efficient for solving only one eigenvalue.

**Comment by LorenzoFioroni** [comment]
This is a comment to allow the Unitary Hack bots to find the PR above ( #149)
