### ISSUE TITLE
Improve the Floquet solver, with the possibility to get also the time-dependent components

### ISSUE THREAD

**Issue by albertomercurio** [qutip/QuantumToolbox.jl#82]
The [current solver for finding the Floquet steady-state](https://github.com/qutip/QuantumToolbox.jl/blob/a227f5f088e555d25810f7ab519d2b860d5f8735/src/steadystate.jl#L69) uses the matrix continued fractions (see, e.g., Supplementary Materials of [^1] to obtain an effective Liouvillian, and then compute the steady-state to it.

Another method would solve instead the full linear system at once:

$$
( \mathcal{L}_0 - i n \omega_d ) \hat{\rho}_n + \mathcal{L}_1 \hat{\rho}\_{n-1} + \mathcal{L}\_{-1} \hat{\rho}\_{n+1} = 0
$$

This is a tridiagonal linear system of the form

$$
\mathbf{A} \cdot \mathbf{b} = 0
$$

where

$$
\mathbf{A} = \begin{pmatrix}
\mathcal{L}\_0 - i (-n\_{\text{max}}) \omega\_{\textrm{d}} & \mathcal{L}\_{-1} & 0 & \cdots & 0 \\
\mathcal{L}_1 & \mathcal{L}_0 - i (-n\_{\text{max}}+1) \omega\_{\textrm{d}} & \mathcal{L}\_{-1} & \cdots & 0 \\
0 & \mathcal{L}\_1 & \mathcal{L}\_0 - i (-n\_{\text{max}}+2) \omega\_{\textrm{d}} & \cdots & 0 \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
0 & 0 & 0 & \cdots & \mathcal{L}_0 - i n\_{\text{max}} \omega\_{\textrm{d}}
\end{pmatrix}
$$

and

$$
\mathbf{b} = \begin{pmatrix}
\hat{\rho}\_{-n_{\text{max}}} \\
\hat{\rho}\_{-n_{\text{max}}+1} \\
\vdots \\
\hat{\rho}\_{0} \\
\vdots \\
\hat{\rho}\_{n_{\text{max}}-1} \\
\hat{\rho}\_{n_{\text{max}}}
\end{pmatrix}
$$

This will allow to simultaneously obtain all the $\hat{\rho}_n$.

The [`steadystate_floquet`](https://github.com/qutip/QuantumToolbox.jl/blob/a227f5f088e555d25810f7ab519d2b860d5f8735/src/steadystate.jl#L69) function has already the argument `lf_solver` that can be used to specify which method to use to get the floquet steadystate.

## References
[^1]: Macrì, Vincenzo, et al. "Spontaneous scattering of Raman photons from cavity-QED systems in the ultrastrong coupling regime." Physical Review Letters 129.27 (2022): 273602.

**Comment by samu-sys** [comment]
This is a comment to allow the Unitary Hack bots to find the PR above ( #153 )
