### ISSUE TITLE
ODE-based `steadystate` solving method

### ISSUE THREAD

**Issue by ytdHuang** [qutip/QuantumToolbox.jl#84]
The current existing [`steadystate`](https://github.com/albertomercurio/QuantumToolbox.jl/blob/d04d1da461982ec42324bdf5a16001928eab49b5/src/time_evolution/time_evolution.jl#L254) solving methods doesn't depend on the initial condition (state), but there are some cases which leads to different stationary states because of the initial states.

By the [`multiple-dispatch`](https://docs.julialang.org/en/v1/manual/methods/) feature of `Julia`, we can have a new `steadystate` method with a given initial state.
The stationary state can be obtained based on [`DiffEqCallbacks.jl`](https://docs.sciml.ai/DiffEqCallbacks/stable/) and the solvers in [`OrdinaryDiffEq.jl`](https://github.com/SciML/OrdinaryDiffEq.jl).

For the terminate condition of finding the stationary state, it would be better to use: 

either the following condition is `true`
$$\lVert\frac{\partial |\rho\rangle\rangle}{\partial t}\rVert \leq \textrm{reltol} \times\lVert\frac{\partial |\rho\rangle\rangle}{\partial t}+|\rho\rangle\rangle\rVert$$

or

$$\lVert\frac{\partial |\rho\rangle\rangle}{\partial t}\rVert \leq \textrm{abstol}$$

**Comment by aarontrowbridge** [comment]
I have begun working on this issue as well. Do you have a degenerate example system in mind to test on?

**Comment by aarontrowbridge** [comment]
I'm also a little confused regarding where the [steady state callback](https://docs.sciml.ai/DiffEqCallbacks/stable/steady_state/) should go. In [`src/steadystate.jl`](https://docs.sciml.ai/DiffEqCallbacks/stable/steady_state/) none of the methods are evolution methods. I could add an evolution method but I'm not sure if that's what you are looking for.

**Comment by ytdHuang** [comment]
> I have begun working on this issue as well. Do you have a degenerate example system in mind to test on?

I don't have a concrete example now.

By utilizing the ODE method, the result is guaranteed to be unique (with the given Liouvillian and initial state)

However, the `SteadyStateDirectSolver` based on `LinearSolve.jl` doesn't guarantee to have a unique solution.

The result obtained from the ODE solver should be the same as the one obtained from `mesolve` (with long enough time evolution).

Besides, I think someone else made a PR #159 ?

**Comment by ilkclord** [comment]
This is a comment to allow the Unitary Hack bots to find the PR above ( #159 )
