### ISSUE TITLE
Support `permute` to re-order the tensor (Kronecker) product

### ISSUE THREAD

**Issue by ytdHuang** [qutip/QuantumToolbox.jl#95]
Support the function [`permute` in `QuTiP`](https://github.com/qutip/qutip/blob/320996bfda3a2eb361eb36cac4208990266b97fe/qutip/core/qobj.py#L1158), something like:

```julia
function permute(A::QuantumObject, order::Vector{Int}) ... end

a = Qobj(rand(2, 2))
b = Qobj(rand(3, 3))
c = Qobj(rand(4, 4))
d = Qobj(rand(5, 5))
abcd = tensor(a, b, c, d)

permute(abcd, [4, 1, 3, 2]) == tensor(d, a, c, b) # true
```

Should support for the following types of quantum object:
- [`KetQuantumObject`](https://github.com/albertomercurio/QuantumToolbox.jl/blob/main/src/quantum_object.jl#L31)
- [`BraQuantumObject`](https://github.com/albertomercurio/QuantumToolbox.jl/blob/main/src/quantum_object.jl#L16)
- [`OperatorQuantumObject`](https://github.com/albertomercurio/QuantumToolbox.jl/blob/main/src/quantum_object.jl#L46)
- [`SuperOperatorQuantumObject`](https://github.com/albertomercurio/QuantumToolbox.jl/blob/main/src/quantum_object.jl#L61)
- [`OperatorKetQuantumObject`](https://github.com/albertomercurio/QuantumToolbox.jl/blob/main/src/quantum_object.jl#L91)
- [`OperatorBraQuantumObject`](https://github.com/albertomercurio/QuantumToolbox.jl/blob/main/src/quantum_object.jl#L76)

**Comment by aarontrowbridge** [comment]
the `tensor` or [`kron`](https://github.com/albertomercurio/QuantumToolbox.jl/blob/5e24d9006f96bba4b1d1169fa4cca5d20ba9d45a/src/quantum_object.jl#L637) function, seems to be only defined for Kets, Bras, and Operators, is it still necessary to write methods for the super operators

**Comment by albertomercurio** [comment]
I can’t figure out what a tensor product between two superoperators should make, physically. So, I think that the definition of tensor product on the superoperators is meaningless

**Comment by aarontrowbridge** [comment]
It is defined in the qutip [`permute`](https://github.com/qutip/qutip/blob/320996bfda3a2eb361eb36cac4208990266b97fe/qutip/core/qobj.py#L1158) for these types but i'm not sure how to think about them either atm.

**Comment by ytdHuang** [comment]
There are some rare situations which we want the `SuperOperator` to be in block matrix form.

Consider a `Operator` with sub-systems $A$ and $B$ ($\mathcal{H}_A \otimes \mathcal{H}_B$). The Hilbert space of it's corresponding `SuperOperator` could be written as:
```math
$$\mathcal{H}_A \otimes \mathcal{H}_B \otimes \mathcal{H}_{A'} \otimes \mathcal{H}_{B'}$$
```
What I have in my mind is some functions that allows me to obtain the `SuperOperator` with the following Hilbert space order:
```math
$$\mathcal{H}_A \otimes \mathcal{H}_{A'} \otimes \mathcal{H}_B \otimes \mathcal{H}_{B'}$$
```

But this could actually be done by transferring the `SuperOperator` back to `Operator` form, apply the `permute`, and then transfer it back to `SuperOperator` type:

```julia
A = Qobj(rand(NA, NA))
B = Qobj(rand(NB, NB))
AB = tensor(A, B)
S = spre(AB) # super operator

op1 = Qobj(S, type = Operator, dims = [NA, NB, NA, NB])
op2 = Apermute(op1, [1, 3, 2, 4])
S_new = Qobj(op2, type = SuperOperator, dims = [NA, NB])
```

So, yes ! 
I think for current stage, we can just focus on `permute` for `Ket`, `Bra`, and `Operator`.

**Comment by aarontrowbridge** [comment]
@ytdHuang thanks for the feedback! I'm in the process of making all of the changes you suggested. I'm in the process of groking what's going on in the `ptrace` function as it relates to permutations, it is definitely a more elegant approach than mine!
